# Generated by Django 5.1.4 on 2025-03-28 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='duracion_min',
        ),
    ]
