# Generated by Django 5.1.4 on 2025-03-19 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Psicologos',
            fields=[
                ('id_psicologo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('especialidad', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='DispositivoUsuario',
            fields=[
                ('id_dispositivo', models.AutoField(primary_key=True, serialize=False)),
                ('user_agent', models.TextField()),
                ('screen_width', models.IntegerField()),
                ('screen_height', models.IntegerField()),
                ('browser', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='EventoUsuario',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('evento', models.CharField(max_length=100)),
                ('id_boton', models.CharField(blank=True, max_length=100, null=True)),
                ('pagina', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('Tarjeta', 'Tarjeta'), ('PayPal', 'PayPal'), ('Transferencia', 'Transferencia')], max_length=50)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], max_length=15)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='DisponibilidadPsicologos',
            fields=[
                ('id_disponibilidad', models.AutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('id_psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.psicologos')),
            ],
        ),
        migrations.CreateModel(
            name='Sesiones',
            fields=[
                ('id_sesion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], max_length=15)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.clientes')),
                ('id_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.pagos')),
                ('id_psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.psicologos')),
                ('id_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.servicios')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialSesiones',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('campo_modificado', models.CharField(max_length=100)),
                ('valor_anterior', models.TextField()),
                ('valor_nuevo', models.TextField()),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True)),
                ('modificado_por', models.CharField(choices=[('psicologo', 'Psicólogo'), ('cliente', 'Cliente'), ('admin', 'Administrador')], max_length=15)),
                ('id_sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.sesiones')),
            ],
        ),
        migrations.CreateModel(
            name='TiempoUsuario',
            fields=[
                ('id_tiempo', models.AutoField(primary_key=True, serialize=False)),
                ('pagina', models.CharField(max_length=255)),
                ('tiempo', models.IntegerField(help_text='Tiempo en milisegundos')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.clientes')),
            ],
        ),
    ]
